task_name: geospatial_dataset_prioritization_v1
description: >
  Identifies and prioritizes the most relevant geospatial datasets (e.g., GIS layers)
  a UK planning officer should consult when evaluating a specific planning application,
  filtering from a provided list of available datasets.

input_schema:
  location_description:
    type: string
    description: "Address or textual description of the site location (e.g., 'Site at 123 Example St, Anytown' or 'Land adjacent to River View, near Anytown Station')."
  application_type:
    type: string
    description: "The type of planning application (e.g., 'Full', 'Outline', 'Listed Building Consent', 'Change of Use'). Provides context for relevance."
  proposed_development_description:
    type: string
    description: "Brief description of the proposed development (e.g., 'Construction of 5 dwellings', 'Extension to industrial unit', 'Alterations to Grade II listed pub', 'Change of use to HMO')."
  known_constraints: # Added this for better prioritization
    type: list
    items:
      type: string
    description: "List of *already known* geospatial constraints affecting the site (e.g., 'Flood Zone 3', 'Within Conservation Area', 'TPO on site'). Used to prioritize verification datasets."
  available_datasets:
    type: list
    items:
      type: string
    description: "The complete list of available geospatial dataset names to filter from."

desired_outputs:
  - prioritized_dataset_list:
      type: list
      items:
        type: string
      description: >
        A prioritized list of dataset names (strings selected ONLY from the `available_datasets` input)
        that are most relevant for assessing the specific application. Typically 10-20 datasets,
        ordered from most to least critical.

domain_constraints:
  - "The output list MUST only contain dataset names exactly as they appear in the `available_datasets` input list."
  - "Prioritization Logic: Datasets must be ordered based on likely relevance/criticality to a planning officer assessing this specific application."
  - "Highest Priority: Datasets needed to *verify* explicitly mentioned `known_constraints` (e.g., 'flood-risk-zone' if 'Flood Zone 3' is known; 'listed-building' if 'Listed Building' is known; 'conservation-area' if 'Conservation Area' is known; 'tree-preservation-zone'/'tree' if 'TPO' is known)."
  - "High Priority: Datasets defining major statutory designations potentially impacted by the `proposed_development_description` or strongly indicated by `location_description` (e.g., 'listed-building', 'conservation-area', 'green-belt', 'area-of-outstanding-natural-beauty', 'site-of-special-scientific-interest', 'scheduled-monument', 'world-heritage-site', 'ramsar'). Elevate priority if `application_type` is specific (e.g., 'Listed Building Consent' makes 'listed-building' primary)."
  - "Medium Priority: Datasets relevant to common planning checks or context even if not explicitly mentioned as constraints (e.g., 'flood-risk-zone', 'tree-preservation-zone'/'tree', 'archaeological-priority-area', 'locally-listed-building', 'central-activities-zone' if applicable, 'brownfield-land'/'brownfield-site'). Also include datasets related to key site features potentially affected by the proposal (e.g., 'tree')."
  - "Contextual Priority: Datasets providing necessary administrative or local context ('local-planning-authority', 'ward', 'parish', 'local-plan-boundary')."
  - "Lower Priority: Datasets representing very broad regions ('region'), very specific/rare designations unlikely to be relevant unless explicitly suggested by context ('battlefield', 'protected-wreck-site', 'heritage-coast'), generic land classifications ('agricultural-land-classification', 'built-up-area' unless proposal is edge-of-settlement), or datasets usually derived *from* other primary data ('heritage-at-risk')."
  - "Filtering: Do NOT include datasets in the output that are clearly irrelevant to the specific context (e.g., don't include 'heritage-coast' for an inner-city site unless there's a very specific reason)."
  - "The output list should typically contain 10-20 dataset names."
  - "The output format must be ONLY a valid JSON list of strings."